
services:
  postgres:
    image: postgres
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: legacy_service
    ports:
      - "5431:5432"  # Map PostgreSQL to 5431 on host
    networks:
      - my_network

  api-gateway:
    container_name: api-gateway
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - '4001:3000'
    env_file:
      - ./api-gateway/.env
    depends_on:
      - postgres
      - redis
      - ingestion
    networks:
      - my_network

  ingestion:
    container_name: ingestion
    build:
      context: ./ingestion
      dockerfile: Dockerfile
    ports:
      - '4002:3000'
    env_file:
      - ./ingestion/.env
    depends_on:
      - postgres
    networks:
      - my_network

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./.data/redis:/data
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
