version: '3.8'

services:
  api-gateway:
    container_name: api-gateway
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./.data/uploads:/usr/src/app/uploads
    depends_on:
      - redis
      - ingestion
  
  ingestion:
    container_name: ingestion
    build:
      context: ./ingestion
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    volumes:
      - ./.data/redis:/data
