version: '3.8'  # Specify the version of the Compose file format

services:
  postgres:
    image: postgres
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: jktech_service
    ports:
      - "5432:5432"
    networks:
      - my_network

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "4001:3000"
    env_file:
      - ./api-gateway/.env
    networks:
      - my_network

  ingestion:
    build:
      context: ./ingestion
      dockerfile: Dockerfile
    container_name: ingestion
    ports:
      - "4002:3000"
    env_file:
      - ./ingestion/.env
    networks:
      - my_network

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./.data/redis:/data
    networks:
      - my_network

networks:
  my_network:
    driver: bridge