name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Install Docker Compose
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.20.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      # Create .env file for api-gateway
      - name: Create .env file for api-gateway
        run: |
          echo "${{ secrets.API_GATEWAY_ENV }}" > ./api-gateway/.env

      # Create .env file for ingestion
      - name: Create .env file for ingestion
        run: |
          echo "${{ secrets.INGESTION_ENV }}" > ./ingestion/.env


      # Check Docker and Docker Compose versions
      - name: Check Docker version
        run: docker --version

      - name: Check Docker Compose version
        run: docker-compose --version

      # Build Docker images
      - name: Build Docker images
        run: docker-compose build

      # Run tests for api-gateway (skip if not ready)
      # Uncomment this when tests are ready
      # - name: Run tests for api-gateway
      #   run: docker-compose run --rm api-gateway npm test

      # Run tests for ingestion (if applicable)
      # Uncomment this when tests are ready
      # - name: Run tests for ingestion
      #   run: docker-compose run --rm ingestion npm test

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.ref == 'refs/heads/main'

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up SSH for deployment
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Deploy to DigitalOcean Droplet
      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no root@142.93.215.48 << 'EOF'
          cd jktech-assignment
          git pull origin main
          docker-compose down
          docker-compose up -d --build
          EOF


          